#!/usr/bin/env python3
"""
Simple Pose Animator - Uses processed character images as different poses
"""
import os
import json

os.environ['HOME'] = '/home/openclaw/.openclaw/workspace/comic_series'
os.environ['XDG_CACHE_HOME'] = '/home/openclaw/.openclaw/workspace/comic_series/.cache'

from PIL import Image

BASE_DIR = "/home/openclaw/.openclaw/workspace/comic_series"
ASSETS = f"{BASE_DIR}/assets"
OUTPUT = f"{BASE_DIR}/assets/output"
POSES_DIR = f"{ASSETS}/characters/nomark/poses"
LOCATIONS_DIR = f"{ASSETS}/locations"

os.makedirs(OUTPUT, exist_ok=True)

def create_scene(background_path, character_path, output_path, char_x=400, char_y=200):
    """Compose a scene with background and character"""
    bg = Image.open(background_path).convert("RGBA")
    # Resize background to standard size
    bg = bg.resize((1280, 720))
    
    char = Image.open(character_path).convert("RGBA")
    # Scale character if needed
    char = char.resize((int(char.width * 0.5), int(char.height * 0.5)))
    
    # Composite
    bg.paste(char, (char_x, char_y), char)
    bg.save(output_path)
    return output_path

def build_scene_library():
    """Build all possible scene combinations"""
    poses = sorted([f for f in os.listdir(POSES_DIR) if f.endswith('.png')])
    locs = sorted([f for f in os.listdir(LOCATIONS_DIR) if f.endswith('.jpg')])[:10]
    
    print(f"Found {len(poses)} poses, {len(locs)} locations")
    
    scenes = []
    for i, pose in enumerate(poses):
        for j, loc in enumerate(locs[:3]):  # Limit for now
            scene_name = f"scene_{i}_{j}.png"
            out_path = f"{OUTPUT}/{scene_name}"
            create_scene(
                f"{LOCATIONS_DIR}/{loc}",
                f"{POSES_DIR}/{pose}",
                out_path,
                char_x=500,
                char_y=250
            )
            scenes.append(scene_name)
            print(f"  ✓ {scene_name}")
    
    return scenes

# Build scenes
print("=== Building Scene Library ===")
scenes = build_scene_library()
print(f"\nGenerated {len(scenes)} scenes in {OUTPUT}")

# Create animation sequence
print("\n=== Creating Animation Sequence ===")
sequence = sorted([f for f in os.listdir(OUTPUT) if f.startswith('scene_')])[:12]

# Save frame list for video
with open(f"{OUTPUT}/frames.txt", "w") as f:
    for frame in sequence:
        f.write(f"file '{frame}'\n")
    f.write("# Generated by pose_animator.py\n")

print(f"Animation frames: {len(sequence)}")
print("Frame list saved to frames.txt")
